# Generated by Django 4.2.9 on 2024-10-15 09:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import elin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=8, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to=elin.models.image_add_elin)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
            options={
                'verbose_name': 'Elin',
                'verbose_name_plural': 'Elin',
                'ordering': ['-created', 'checked'],
            },
        ),
        migrations.CreateModel(
            name='ElinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Elin kategoriýa',
                'verbose_name_plural': 'Elin kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='ImageElin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=elin.models.images_add_elin, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty')),
                ('elin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='elin.elin', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Elin surat',
                'verbose_name_plural': 'Elin suratlar',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='elin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elin.elincategory'),
        ),
    ]
