# Generated by Django 4.2.9 on 2024-06-25 13:11

from django.db import migrations, models
import django.db.models.deletion
import elin.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Elin kategoriýa',
                'verbose_name_plural': 'Elin kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='Elin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('img1', models.ImageField(null=True, upload_to=elin.models.image_add_elin)),
                ('img2', models.ImageField(null=True, upload_to=elin.models.image_add_elin)),
                ('img3', models.ImageField(null=True, upload_to=elin.models.image_add_elin)),
                ('img4', models.ImageField(null=True, upload_to=elin.models.image_add_elin)),
                ('img5', models.ImageField(null=True, upload_to=elin.models.image_add_elin)),
                ('text', tinymce.models.HTMLField()),
                ('created', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elin.elincategory')),
            ],
            options={
                'verbose_name': 'Elin',
                'verbose_name_plural': 'Elin',
            },
        ),
    ]
