# Generated by Django 5.0.7 on 2024-08-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elin', '0003_rename_img1_elin_img_remove_elin_img2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elin',
            options={'ordering': ['-created', 'checked'], 'verbose_name': 'Elin', 'verbose_name_plural': 'Elin'},
        ),
        migrations.AlterModelOptions(
            name='imageelin',
            options={'ordering': ['-created'], 'verbose_name': 'Elin surat', 'verbose_name_plural': 'Elin suratlar'},
        ),
        migrations.AlterField(
            model_name='elin',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imageelin',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty'),
        ),
    ]
