# Generated by Django 4.2.9 on 2024-10-11 12:25

import ckeditor.fields
from django.db import migrations, models
import elin.models


class Migration(migrations.Migration):

    dependencies = [
        ('elin', '0004_alter_elin_options_alter_imageelin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elin',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='imageelin',
            name='img',
            field=models.ImageField(null=True, upload_to=elin.models.images_add_elin, verbose_name='Surat'),
        ),
    ]
