# Generated by Django 5.0.7 on 2024-08-05 20:45

import django.db.models.deletion
import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_phone_alter_service_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='img1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='service',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='service',
            name='img5',
        ),
        migrations.CreateModel(
            name='ImageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=service.models.image_add_hyzmat, verbose_name='Surat')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Döredilen wagty')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service.service', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Hyzmat surat',
                'verbose_name_plural': 'Hyzmat suratlar',
            },
        ),
    ]
