# Generated by Django 5.0.7 on 2024-07-25 17:44

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.ImageField(null=True, upload_to='carousel')),
            ],
            options={
                'verbose_name': 'Banner surat',
                'verbose_name_plural': 'Banner suratlar',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Habar kategoriýa',
                'verbose_name_plural': 'Habar kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='UserProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=11, null=True)),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ulanyjy',
                'verbose_name_plural': 'Ulanyjylar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=150, null=True)),
                ('img', models.ImageField(null=True, upload_to=api.models.image_add_habar)),
                ('text', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newscategory')),
            ],
            options={
                'verbose_name': 'Habar',
                'verbose_name_plural': 'Habarlar',
            },
        ),
        migrations.CreateModel(
            name='TopProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('img1', models.ImageField(default='/static/', null=True, upload_to=api.models.image_add_top)),
                ('img2', models.ImageField(null=True, upload_to=api.models.image_add_top)),
                ('img3', models.ImageField(null=True, upload_to=api.models.image_add_top)),
                ('img4', models.ImageField(null=True, upload_to=api.models.image_add_top)),
                ('img5', models.ImageField(null=True, upload_to=api.models.image_add_top)),
                ('text', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
            options={
                'verbose_name': 'Saýlanan',
                'verbose_name_plural': 'Saýlananlar',
            },
        ),
    ]
