# Generated by Django 4.2.10 on 2024-03-11 10:55

import api.models
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Awtoulag kategoriýa',
                'verbose_name_plural': 'Awtoulag kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.ImageField(null=True, upload_to='carousel')),
            ],
        ),
        migrations.CreateModel(
            name='ElinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Elin kategoriýa',
                'verbose_name_plural': 'Elin kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='LogistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Logistika kategoriýa',
                'verbose_name_plural': 'Logistika kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Habar kategoriýa',
                'verbose_name_plural': 'Habar kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='OtherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Beýleki kategoriýa',
                'verbose_name_plural': 'Beýleki kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Hyzmat kategoriýa',
                'verbose_name_plural': 'Hyzmat kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='TopProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('img1', models.ImageField(default='/static/', null=True, upload_to='saýlanan')),
                ('img2', models.ImageField(null=True, upload_to='saýlanan')),
                ('img3', models.ImageField(null=True, upload_to='saýlanan')),
                ('img4', models.ImageField(null=True, upload_to='saýlanan')),
                ('img5', models.ImageField(null=True, upload_to='saýlanan')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
            options={
                'verbose_name': 'Saýlanan',
                'verbose_name_plural': 'Saýlananlar',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('img1', models.ImageField(null=True, upload_to='hyzmatlar')),
                ('img2', models.ImageField(null=True, upload_to='hyzmatlar')),
                ('img3', models.ImageField(null=True, upload_to='hyzmatlar')),
                ('img4', models.ImageField(null=True, upload_to='hyzmatlar')),
                ('img5', models.ImageField(null=True, upload_to='hyzmatlar')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicecategory')),
            ],
            options={
                'verbose_name': 'Hyzmatlar',
                'verbose_name_plural': 'Hyzmatlar',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('img1', models.ImageField(null=True, upload_to='beylekiler')),
                ('img2', models.ImageField(null=True, upload_to='beylekiler')),
                ('img3', models.ImageField(null=True, upload_to='beylekiler')),
                ('img4', models.ImageField(null=True, upload_to='beylekiler')),
                ('img5', models.ImageField(null=True, upload_to='beylekiler')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.othercategory')),
            ],
            options={
                'verbose_name': 'Beylekiler',
                'verbose_name_plural': 'Beylekiler',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=150, null=True)),
                ('img', models.ImageField(null=True, upload_to='habarlar')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newscategory')),
            ],
            options={
                'verbose_name': 'Habar',
                'verbose_name_plural': 'Habarlar',
            },
        ),
        migrations.CreateModel(
            name='Logist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('img1', models.ImageField(null=True, upload_to='logistika')),
                ('img2', models.ImageField(null=True, upload_to='logistika')),
                ('img3', models.ImageField(null=True, upload_to='logistika')),
                ('img4', models.ImageField(null=True, upload_to='logistika')),
                ('img5', models.ImageField(null=True, upload_to='logistika')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.logistcategory')),
            ],
            options={
                'verbose_name': 'Logistika',
                'verbose_name_plural': 'Logistikalar',
            },
        ),
        migrations.CreateModel(
            name='Elin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('class_type', models.CharField(choices=[('hyzmatlar', 'Hyzmatlar'), ('elin', 'Elin'), ('beýlekiler', 'Beýlekiler')], max_length=100, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('img1', models.ImageField(null=True, upload_to='elin')),
                ('img2', models.ImageField(null=True, upload_to='elin')),
                ('img3', models.ImageField(null=True, upload_to='elin')),
                ('img4', models.ImageField(null=True, upload_to='elin')),
                ('img5', models.ImageField(null=True, upload_to='elin')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elincategory')),
            ],
            options={
                'verbose_name': 'Elin',
                'verbose_name_plural': 'Elin',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('img1', models.ImageField(null=True, upload_to='ulaglar')),
                ('img2', models.ImageField(null=True, upload_to='ulaglar')),
                ('img3', models.ImageField(null=True, upload_to='ulaglar')),
                ('img4', models.ImageField(null=True, upload_to='ulaglar')),
                ('img5', models.ImageField(null=True, upload_to='ulaglar')),
                ('text', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carcategory')),
            ],
            options={
                'verbose_name': 'Ulag',
                'verbose_name_plural': 'Ulaglar',
            },
        ),
        migrations.CreateModel(
            name='AddedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('img1', models.ImageField(null=True, upload_to=api.models.image_add)),
                ('img2', models.ImageField(null=True, upload_to=api.models.image_add)),
                ('img3', models.ImageField(null=True, upload_to=api.models.image_add)),
                ('img4', models.ImageField(null=True, upload_to=api.models.image_add)),
                ('img5', models.ImageField(null=True, upload_to=api.models.image_add)),
                ('text', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.logistcategory')),
            ],
            options={
                'verbose_name': 'Gosulan',
                'verbose_name_plural': 'Gosulanlar',
            },
        ),
        migrations.CreateModel(
            name='UserProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('author', models.CharField(max_length=23, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Ulanyjy',
                'verbose_name_plural': 'Ulanyjylar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
