# Generated by Django 5.0.7 on 2024-08-02 21:29

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topproducts',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='topproducts',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='topproducts',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='topproducts',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='topproducts',
            name='img5',
        ),
        migrations.AddField(
            model_name='topproducts',
            name='img',
            field=models.ImageField(null=True, upload_to=api.models.image_add_top, verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Salgy'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='img',
            field=models.ImageField(null=True, upload_to='carousel', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=150, null=True, verbose_name='Awtor'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newscategory', verbose_name='Kategoriýa'),
        ),
        migrations.AlterField(
            model_name='news',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Barlandy'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Döredilen wagty'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(null=True, upload_to=api.models.image_add_habar, verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True, verbose_name='Maglumat'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Habar kategoriýa'),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address', verbose_name='Salgy'),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='Awtor'),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='category',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriýa'),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Barlandy'),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Döredilen wagty'),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='phone',
            field=models.CharField(max_length=8, null=True, verbose_name='Telefon belgi'),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='price',
            field=models.CharField(max_length=100, null=True, verbose_name='Bahasy'),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='text',
            field=models.TextField(blank=True, verbose_name='Maglumat'),
        ),
        migrations.AlterField(
            model_name='userprod',
            name='author',
            field=models.CharField(max_length=8, null=True, verbose_name='Awtor'),
        ),
        migrations.AlterField(
            model_name='userprod',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Barlandy'),
        ),
        migrations.CreateModel(
            name='ImageTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=api.models.image_add_top, verbose_name='Surat')),
                ('top', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.topproducts', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Saýlanan surat',
                'verbose_name_plural': 'Saýlanan suratlar',
            },
        ),
    ]
