# Generated by Django 4.2.9 on 2024-07-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_news_text_alter_userprod_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprod',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
