# Generated by Django 5.0.7 on 2024-08-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_topproducts_img1_remove_topproducts_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetop',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Döredilen wagty'),
        ),
    ]
