# Generated by Django 5.0.7 on 2024-08-05 18:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imagetop_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetop',
            name='img',
            field=models.ImageField(null=True, upload_to=api.models.images_add_top, verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Telefon belgi'),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Bahasy'),
        ),
    ]
