# Generated by Django 4.2.9 on 2024-07-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprod_checked'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprod',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprod',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userprod',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprod',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprod',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprod',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprod',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprod',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userprod',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprod',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprod',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprod',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userprod',
            name='username',
        ),
    ]
