# Generated by Django 4.2.9 on 2024-07-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprod_managers_remove_userprod_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprod',
            name='author',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
