# Generated by Django 5.0.7 on 2024-08-05 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_imagetop_img_alter_topproducts_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetop',
            name='top',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.topproducts', verbose_name='Haryt'),
        ),
    ]
