# Generated by Django 5.0.4 on 2024-04-27 02:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_addedmodel_img1_alter_addedmodel_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logist',
            name='bring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logist',
            name='last_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='logist',
            name='nirden',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logist',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logist',
            name='where',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addedmodel',
            name='img1',
            field=models.ImageField(null=True, upload_to=api.models.image_add),
        ),
        migrations.AlterField(
            model_name='addedmodel',
            name='img2',
            field=models.ImageField(null=True, upload_to=api.models.image_add),
        ),
        migrations.AlterField(
            model_name='addedmodel',
            name='img3',
            field=models.ImageField(null=True, upload_to=api.models.image_add),
        ),
        migrations.AlterField(
            model_name='addedmodel',
            name='img4',
            field=models.ImageField(null=True, upload_to=api.models.image_add),
        ),
        migrations.AlterField(
            model_name='addedmodel',
            name='img5',
            field=models.ImageField(null=True, upload_to=api.models.image_add),
        ),
    ]
