# Generated by Django 5.0.6 on 2024-06-22 05:25

import api.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_logist_bring_logist_last_date_logist_nirden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logist',
            name='images',
        ),
        migrations.AlterField(
            model_name='addedmodel',
            name='img1',
            field=models.ImageField(null=True, upload_to=api.models.image_add),
        ),
        migrations.AlterField(
            model_name='addedmodel',
            name='img2',
            field=models.ImageField(null=True, upload_to=api.models.image_add),
        ),
        migrations.AlterField(
            model_name='addedmodel',
            name='img3',
            field=models.ImageField(null=True, upload_to=api.models.image_add),
        ),
        migrations.AlterField(
            model_name='addedmodel',
            name='img4',
            field=models.ImageField(null=True, upload_to=api.models.image_add),
        ),
        migrations.AlterField(
            model_name='addedmodel',
            name='img5',
            field=models.ImageField(null=True, upload_to=api.models.image_add),
        ),
        migrations.AlterField(
            model_name='car',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='elin',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='logist',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='other',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
