# Generated by Django 4.2.9 on 2024-10-11 12:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_news_options_alter_topproducts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='api.userprod', verbose_name='Ulanyjy')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokenler',
            },
        ),
    ]
