# Generated by Django 4.2.9 on 2024-10-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprod_managers_remove_userprod_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='Ady'),
        ),
    ]
