# Generated by Django 5.0.7 on 2024-08-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_rename_img1_other_img_remove_other_img2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageother',
            options={'ordering': ['created'], 'verbose_name': 'Beyleki surat', 'verbose_name_plural': 'Beyleki suratlar'},
        ),
        migrations.AlterModelOptions(
            name='other',
            options={'ordering': ['-created', 'checked'], 'verbose_name': 'Beylekiler', 'verbose_name_plural': 'Beylekiler'},
        ),
        migrations.AlterField(
            model_name='imageother',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty'),
        ),
        migrations.AlterField(
            model_name='other',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
