# Generated by Django 4.2.9 on 2024-10-11 12:25

import ckeditor.fields
from django.db import migrations, models
import other.models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0004_alter_imageother_options_alter_other_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageother',
            name='img',
            field=models.ImageField(null=True, upload_to=other.models.images_add_beyleki, verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='other',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
