# Generated by Django 4.2.9 on 2024-06-25 13:12

from django.db import migrations, models
import django.db.models.deletion
import logist.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Logistika kategoriýa',
                'verbose_name_plural': 'Logistika kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='Logist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=255, null=True)),
                ('where', models.CharField(max_length=255, null=True)),
                ('nirden', models.CharField(max_length=255, null=True)),
                ('last_date', models.DateField(null=True)),
                ('bring', models.BooleanField(default=False)),
                ('vip', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('img1', models.ImageField(null=True, upload_to=logist.models.image_add_logist)),
                ('img2', models.ImageField(null=True, upload_to=logist.models.image_add_logist)),
                ('img3', models.ImageField(null=True, upload_to=logist.models.image_add_logist)),
                ('img4', models.ImageField(null=True, upload_to=logist.models.image_add_logist)),
                ('img5', models.ImageField(null=True, upload_to=logist.models.image_add_logist)),
                ('text', tinymce.models.HTMLField()),
                ('created', models.DateField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logist.logistcategory')),
            ],
            options={
                'verbose_name': 'Logistika',
                'verbose_name_plural': 'Logistikalar',
            },
        ),
    ]
