# Generated by Django 5.0.7 on 2024-07-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logist',
            name='nirden',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='logist',
            name='where',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
