# Generated by Django 5.0.7 on 2024-08-05 20:45

import django.db.models.deletion
import logist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logist', '0003_alter_logist_phone_alter_logist_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logist',
            old_name='img1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='logist',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='logist',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='logist',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='logist',
            name='img5',
        ),
        migrations.CreateModel(
            name='ImageLogist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=logist.models.image_add_logist, verbose_name='Surat')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Döredilen wagty')),
                ('logist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logist.logist', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Logistika surat',
                'verbose_name_plural': 'Logistika suratlar',
            },
        ),
    ]
