# Generated by Django 5.0.7 on 2024-08-22 14:19

import logist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logist', '0004_rename_img1_logist_img_remove_logist_img2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagelogist',
            options={'ordering': ['-created'], 'verbose_name': 'Logistika surat', 'verbose_name_plural': 'Logistika suratlar'},
        ),
        migrations.AlterModelOptions(
            name='logist',
            options={'ordering': ['checked', '-created'], 'verbose_name': 'Logistika', 'verbose_name_plural': 'Logistikalar'},
        ),
        migrations.AlterField(
            model_name='imagelogist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty'),
        ),
        migrations.AlterField(
            model_name='imagelogist',
            name='img',
            field=models.ImageField(null=True, upload_to=logist.models.images_add_logist, verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='logist',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
