# Generated by Django 4.2.9 on 2024-10-11 12:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logist', '0005_alter_imagelogist_options_alter_logist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logist',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
