# Generated by Django 4.2.9 on 2024-10-15 09:58

import car.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=8, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to=car.models.image_add_car)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
            options={
                'verbose_name': 'Awotulag',
                'verbose_name_plural': 'Awtoulaglar',
                'ordering': ['-created', 'checked'],
            },
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Awtoulag kategoriýa',
                'verbose_name_plural': 'Awtoulag kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='ImageCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=car.models.images_add_car, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car.car', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Awtoulag surat',
                'verbose_name_plural': 'Awtoulag suratlar',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carcategory'),
        ),
    ]
