# Generated by Django 5.0.7 on 2024-08-05 20:45

import car.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_phone_alter_car_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='img1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='car',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='img5',
        ),
        migrations.CreateModel(
            name='ImageCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=car.models.image_add_car, verbose_name='Surat')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Döredilen wagty')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car.car', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Awtoulag surat',
                'verbose_name_plural': 'Awtoulag suratlar',
            },
        ),
    ]
