# Generated by Django 5.0.7 on 2024-08-22 14:19

import car.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_rename_img1_car_img_remove_car_img2_remove_car_img3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created', 'checked'], 'verbose_name': 'Awotulag', 'verbose_name_plural': 'Awtoulaglar'},
        ),
        migrations.AlterModelOptions(
            name='imagecar',
            options={'ordering': ['created'], 'verbose_name': 'Awtoulag surat', 'verbose_name_plural': 'Awtoulag suratlar'},
        ),
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imagecar',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty'),
        ),
        migrations.AlterField(
            model_name='imagecar',
            name='img',
            field=models.ImageField(null=True, upload_to=car.models.images_add_car, verbose_name='Surat'),
        ),
    ]
