# Generated by Django 4.2.9 on 2024-10-11 12:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_options_alter_imagecar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
